---
title: "Hydra Methology"
output: pdf_document
bibliography: references.bib
link-citations: yes
urlcolor: blue
---

<!--# Drafting notes
Using organization of MS_SCAA methodology as a template

Also compare with Vanessa’s multiple species state space model: 
https://github.com/vtrijoulet/Multisp_model_JAE (link to paper)
https://github.com/vtrijoulet/MS_SSM (link to up to date model) -->

## Introduction 

The original purpose of the Hydra simulation model was to create simulated data for testing simpler multispecies assessment models [@gaichas_combining_2017]. Further model development repurposed Hydra as an MSE tool to test proposed multispecies and ecosystem level management procedures to support EBFM analyses for the New England Fishery Management Council, and were reviewed in 2018 as part of an [Ecosystem Based Management Strategy Review for Georges Bank](https://www.fisheries.noaa.gov/resource/peer-reviewed-research/ecosystem-based-fisheries-management-strategy-review-georges-bank). . 
 
The current Hydra estimation model can still be used for the above purposes (no simulation code was removed), but with the potential added benefit of estimating operating model parameters by fitting to data from the ecosystem, rather than iterative hand calibration. 

Multispecies models “of intermediate complexity” between single population and full ecosystem models potentially combine the best aspects of current single species assessment models (including demographic structure and statistical parameter estimation) with key ecological linkages between species (Plagányi et al. 2012, Collie et al. 2014). The Northeast Fisheries Science Center (NEFSC) is currently applying multispecies production and delay-difference models to a simulated system coarsely modeled after the Georges Bank fish community. The focus of this work is to evaluate the performance of a length-based multispecies approach for providing management advice. While we do not yet have a fitted model ready to provide catch advice, this review should identify next steps for further developing model code, inputs, and diagnostics towards this goal.

To evaluate Hydra’s performance as an estimation model, we converted it from a simulation model by incorporating likelihood functions to fit the model to time series of aggregate fishery catch, survey biomass, size compositions from the fishery and survey, and length-specific predator diets. Assessment model performance evaluation is in progress by comparing “true” biomass, abundance, and fishing mortality rates to model-estimated quantities using skill assessment metrics (e.g., correlation, RMSE, Modeling efficiency; Stow et al. 2009). Finally, the length-based multispecies model is being fit to actual observations from Georges Bank to evaluate operational potential within a particular region. 


## Methodology 

The reviewed model is based on the simulation model Hydra [@gaichas_combining_2017], implemented in ADMB [@fournier_ad_2012]. Hydra's structure  is derived from the length-based multispecies simulation model, LeMANS [@hall_length-based_2006; @rochet_does_2011], with additional options for growth, and recruitment functional forms and more detailed fishing fleets.

A key feature of Hydra that differentiates it from LeMANS and other length-based models is its treatment of length information. Attempting to balance model complexity and run time with available data and adequately modeling length-based processes, Hydra applies an equal number of length bins to all modeled species. The modeler specifies the overall number of bins (5 in the original simulation model), and the size in cm spanned by each bin for each species. The original Hydra simulation model used narrower length bins for smaller fish sizes and a length bin spanning a wider range of sizes for larger fish to efficiently represent changes size selectivity of predators and fisheries. The estimation model uses equal width bins equally dividing each species' maximum observed length into the overall number of bins. 

Modeler decisions on length bin number and width combined with individual species growth parameters both contribute to the model temporal scale, which internally calculated and set equal to the time required for the fastest-growing species to grow out of its smallest length bin (if that is less than one year). Therefore, model timesteps will never exceed one year, but can be subannual.

For this review, the simulation model code was forked and an objective function added, with modifications to the data section to accommodate new data inputs and to the parameter section to estimate fishery and survey selectivity and catchability. As an estimation model, Hydra can be fitted to multiple data streams. Currently the objective function comprises the following components, catch (by species for each fleet), size composition of the catch (by species for each fleet), survey abundance index (by species for each survey), survey size composition (by species for each survey), survey diet composition (stomach weight by predator size bin for each predator species and survey), and recruitment (annual deviations from mean recruitment by species). A detailed description of the objective function equations is available [here](https://drive.google.com/drive/folders/1Cx4J1hToM2WgfUQjH_9rC7Hg81tTuIxU). 

Hydra input files were developed directly from `mskeyrun` datasets by modifying functions in Andy Beet's `hydradata` R package. The function `create_Rdata_mskeyrun.R` ([code](https://github.com/thefaylab/hydradata/blob/master/data-raw/create_RData_mskeyrun.R)) allows the user to specify whether datasets should be constructed from Atlantis-simulated or real Georges Bank data, and the number of length bins to use for composition data, then creates an R data object. This data object is then used to create data and parameter input files using the function `hydradata::create_datpin_files()`. 

Hydra output visualizations were developed to evaluate model fits with different settings and input datasets. The current diagnostics include model fits to each survey index, model fits to catch by fleet, comparisons of estimated and observed length compositions by year and in aggregate across years for each modeled species, residuals of fits to length compositions, and comparisons of estimated and observed diet composition. In addition, model outputs of estimated recruitment, total biomass, fishery and survey selectivity, fishing mortality, and predation mortality are produced. Initial model skill assessment compares model output total biomass with known total biomass for the simulated datasets.  

All model code, data processing, and visualization is available online: 

*  Hydra model estimation version code  https://github.com/thefaylab/hydra_sim  
*  Hydra estimation model data file generation https://github.com/thefaylab/hydradata  
*  Hydra model diagnostics https://github.com/thefaylab/hydra_diag  

### Data requirements

A common dataset for 10 Georges Bank species has been developed, as well as a simulated dataset for model performance testing. This `mskeyrun` data package holds both datasets. All modeling teams used these datasets. Group decisions on data are also documented below.

**Years:** 1968-2019

**Area:** Georges Bank (see map above)

**Species:**  Atlantic cod (*Gadus morhua*), Atlantic herring (*Clupea harengus*), Atlantic mackerel (*Scomber scombrus*), Goosefish (*Lophius americanus*), Haddock (*Melanogrammus aeglefinus*), Silver hake (*Merluccius bilinearis*), Spiny dogfish (*Squalus acanthias*), Winter flounder (*Pseudopleuronectes americanus*), Winter skate (*Leucoraja ocellata*), and Yellowtail flounder (*Limanda ferruginea*) 


### Model description

Much of the material below is edited from from @gaichas_combining_2017, supplementary material]:
 
>Hydra is a length-based multispecies, multifleet model designed to provide simulated data for performance testing of simpler (non-size structured) multispecies assessment models and management procedures for the Northeast U.S. Continental Shelf. 
 
>We focus on body size rather than age because:
 
>*  Predation is a length-based process
>*  Harvesting is a length-based process
>*  Routine age determinations are not available for all ecologically and economically important species
 
#### Population dynamics

For an individual species $i$, the number of individuals $N$ in size class $j$ at time $t+1$ represent the survivors from that cohort from the previous time step ($t$) that have not grown into a larger size class, plus the number of individuals growing into size class $j$ from smaller size classes during the time interval. We only consider transitions among immediately adjacent size classes. For size classes larger than the recruit (smallest) size class, the model for each species $i$ can be written:

$$ N_{i,j,t+1} = \sum_{j'}{\phi_{i,j' \to j,t}S_{i,j',t}N_{i,j',t}} $$

The proportion surviving from size class $j-1$ to size class $j$ for a species at time $t$ is denoted $S_{j',t}$,.  $\phi_{j’ \to j}$ is the probability of moving from size class $j-1$ to size class $j$.


##### Growth and Time-in-Stage 

The values for $\phi_{j’ \to j,t}$, the time required for an individual to grow between length bins are determined from the growth function. Growth can be assumed to follow a von Bertalanffy (see @hall_length-based_2006) or power function, either of which can be applied to any species. As in @hall_length-based_2006, the model timestep is set up to equal the amount of time it takes for the fastest growing species/length bin combination to grow into the next length bin. 

One of the simplest possible models for indeterminate growth with environmental effects is exponential: 

$$l_{i,a,t}=\Psi_ia_i^{K_i}e^{\sum{\delta_pX_{p,t}}}$$

where $l_{i,a,t}$ is the length of species $i$, age $a$ and time $t$; $\Psi_i$ and $K_i$ are growth model parameters, $\delta_t$ is the effect of the pth covariate on growth, and $X_{p,t}$ is the pth covariate at time $t$. While we show the full potential model here, no covariates on growth were included in model fits.

The time required to grow through a specified length interval $lb$ is: 

$$\Delta t_i=\left[  \frac{\Delta lb_i } {\Psi_i e^{\sum{\delta_pX_{p,t}}} }  \right]^{1/K_i}$$

and the expression for the probability $\phi$ of moving through the length interval is then: 

$$\phi_i=\frac{1}{\Delta t_i}$$

Von Bertalanffy growth is modeled identically as in @hall_length-based_2006: 

$$l_{i,t}=L_{\infty i}(1-e^{-vonBK_i, (t-t_{0,i})})$$

with the time required to grow through a specified length interval: 

$$\Delta t_i=\frac{1}{vonBK_i}log\left[  \frac{L_{\infty i}-lb_{lower,i}}{L_{\infty i}-lb_{upper,i}}   \right]$$

and an identical expression for the probability of moving through the length interval as above. 

##### Recruitment

<!-- Three spawner-recruit functional forms are currently implemented along with a model-free average recruitment with deviations option.  In the current model configuration, recruits are individuals entering size class 1 during the each year’s first model timestep. The Deriso-Schnute spawner recruit model (Quinn and Deriso, 1999) is also included as an option for recruitment, but has not yet been parameterized and so is not included in detail here. A fifth function for egg production-based recruitment is similarly implemented in the model code but has not been successfully parameterized, so is also omitted from this description. -->

###### Average recruitment with annual deviations

In the most basic formulation, no spawner-recruit model is specified, but annual log deviations $\Lambda_{i,t}$ from mean log recruitment $\bar{R}_i$ determine annual recruitment levels:
$$N_{i,1,t}=e^{\bar{R}_i+\Lambda_{i,t}}$$
<!-- SKG: if we only intend to fit average recruitment with deviations, we could leave the parametric recruitment functions out here and supply only dummy variables for those to the model in the dat/pin file-->

<!-- ###### Maturity and Spawning Stock Biomass (SSB) based recruitment -->

<!-- Evidence for density-dependent maturation has emerged for a number of groundfish species in this region.  There may also be other environmental effects on maturation. We will accommodate this possibility in the expression for the proportion of mature individuals at size: -->

<!--      (9), -->
<!-- where pi,j,t is the proportion mature for species i, length j, and time t;  ν, and ωi are maturity model parameters; ςm is a coefficient for the mth covariate, Vm,; and l is the midpoint of the jth length interval. Similarly to growth, we do not include environmental covariates on maturation in the simulations presented here. -->

<!-- Spawning stock biomass (SSB) in this model includes both male and female fish, and is therefore the proportion mature times numbers times weight, pi,j,k,t Ni,j,k,t Wi,j,k, with W representing the mean weight at length j for species i. -->

<!--      (10), -->
<!-- Standard Ricker and Beverton-Holt recruitment functional forms are included. In addition, a three parameter gamma function employs a generalized Ricker model that can accommodate environmental or ecological terms: -->


<!-- where  Ni,1,t is the number of recruits of species i, size class 1, and time t; αi,k is density-independent recruitment parameter for species i; SSBi,t-r is spawning stock biomass of species i and time t-r; r is the time delay between spawning and recruitment; γi is a shape parameter, βi is a stock-dependent coefficient, ζp is the effect of the pth covariate on recruitment of species i, and Xp is the pth covariate at time t-q (where q≤r).  The covariates can include physical terms (e.g. temperature) and/or ecological terms (e.g. predator abundance, competitor abundance etc.); however we note that environmental covariates on recruitment are not used in these simulations.  -->

##### Mortality

The survival rate is:
$$S_{i,j,t}=e^{-(M1_{i,j}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t})}$$

The rate of natural mortality is partitioned into two components: sources of natural mortality due to all unmodeled factors ($M1$) and predation mortality from species included in the model ($M2$). 

The predation process is decomposed into size selectivity and species vulnerability in each area. The $\rho$, of prey species $m$ size $n$ for a given predator species $i$ size $j$ is:
$$\rho_{i,j,m,n} = \vartheta_{n,j}\lambda_{m,i}$$

where $\vartheta_{n,j}$ is the preference for a prey item of size $n$ by predator size $j$, and $\lambda_{m,i}$ is the vulnerability of prey species $m$ to predator species $i$. The parameter $\lambda$ is set to either 0 or 1 depending on whether predator $i$ is known to prey on species $m$.

The size preference function is: 
$$\vartheta_{n,j} = \frac{1}{(w_n / w_j)\sigma_j \sqrt{2\pi}} e^{-\frac{[log_e(w_n / w_j) - \Psi_j]}{2\sigma_j^2}}$$

where $w_n$ is the weight at the midpoint of the length bin for a prey of size $n$, $w_j$ is the weight at the midpoint of the length bin for a predator of size $j$, $\Psi_j$ is the 'preferred' predator/prey weight ratio on a logarithmic scale, and $\sigma_j^2$ is the variance in predator size preference.  

To estimate the daily food intake $I$ for each predator, we use:
<!-- SKG: could not find the original Russian alphabet characters used in the pub, delta and omega are used in growth equations, need to fix this. --> 

$$I_{i,j,t} = 24 [\delta_i e^{\omega_i T}]\bar{C}_{i,j,k,t}$$

where the term in brackets gives the temperature ($T$)-dependent hourly consumption rate with parameters $\delta_i$ and $\omega_i$ and $\bar{C}_{i,j,k,t}$ is the mean stomach content weight (g) over a diel cycle.

The predation mortality rate on a particular prey species depends on the total consumption by predators, the suitability of that prey to each predator, and the total suitable prey biomass available to each of its predators. If the predation functional feeding response is assumed to be a Holling Type II, the $M2$ component on prey species $m$ size $n$ is then (Hall et al., 2006; Magnússon, 1995):
<!--
*copied from [Sarah's presentation](https://noaa-edab.github.io/presentations/20201008_FIT_MSmods_Gaichas.html), ([source file](https://github.com/NOAA-EDAB/presentations/blob/master/Workshops/FIT_MultispeciesMods_2020-10-08/20201008_FIT_MSmods_Gaichas.Rmd)) need to ensure I used consistent notation*
--> 

$$M2_{m,n,t} = \sum_i \sum_j I_{i,j,t} N_{i,j,t} \frac{\rho_{i,j,m,n}}{\sum_a \sum_b \rho_{i,j,a,b} W_{a,b} N_{a,b} + \Omega}$$

where $a$ and $b$ represent all prey species and sizes for predator $i$, $W$ is the mean weight of prey $a$ in size class $b$, $\Omega$ is ‘other’ food not explicitly included in the model, and all other terms are as above.

<!-- SKG: Selectivity function may need rethinking --> 

Fishing mortality is also size-specific.  The selectivity for a specified gear type $q$ is given by:
$$s_{i,j,q}=[1+e^{-(c_{i,q}+d_{i,q}l)}]^{-1}$$ 

where $c_{i,j,q}$  and  $d_{i,j,q}$  are model parameters and $l$ is the midpoint of the $j$th length interval.

<!-- SKG: Fishing may need rethinking, in particular fleet definitions --> 

<!-- add new F equation -->


The yield from species $i$ at time $t$ is then:
$$Y_{i,t} = \sum_j \sum_q \frac{s_{i,j,q}F_{i,j,q,t}}{M1_{i,j}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t}} [1-e^{-(M1_{i,j}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t})}] N_{i,j,t}W_{i,j}$$

where $W_{i,j,k}$  is the mean weight of an individual of species $i$ and length $j$. 

### Objective Function

The model can be fitted to multiple data streams. Currently the objective function comprises the following components, catch (by species for each fleet), size composition of the catch (by species for each fleet), survey abundance index (by species for each survey), survery size composition (by species for each survey), survey diet composition (stomach weight by predator size bin for each predator species and survey), and recruitment (annual deviations from mean recruitment by species).  

#### Catch 

Expected catch for species $i$ in fleet $q$ is summed over time steps to the fishing/calendar year $y$.

$$ \hat{C}_{y,i,q} = \sum_{t \in y} \sum_{j} \frac{s_{i,j,q}F_{i,j,q,t}}{M1_{i,j,t}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t}} \left[ 1 - e^{-(M1_{i,j,t}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t})} \right] N_{i,j,t} W_{i,j,t}$$

$$ ln(C_{y,i,q}) \sim \mathcal{N}(ln(\hat{C}_{y,i,q}), \sigma^{2}_{q,i,y}) $$


#### Catch length composition

$$ \hat{p}_{q,i,y,j} = p^{*}_{q,i,y,j} / \sum_{j'}{p^{*}_{q,i,y,j'}} $$

$$ p^{*}_{q,i,y,j} = \sum_{t \in y} \frac{s_{i,j,q}F_{i,j,q,t}}{M1_{i,j,t}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t}} \left[ 1 - e^{-(M1_{i,j,t}+M2_{i,j,t}+s_{i,j,q}F_{i,j,q,t})} \right] N_{i,j,t}$$

Proportions at length (in numbers) in catch for each species in each fleet are modeled as multinomial,  given an input annual sample size for each composition.  

#### Survey abundance indices

The predicted values for survey abundance rely on the timing of the survey within a year, catchability of the species in the survey, and the (length-based) survey selectivity. Survey $g$ predicted values (in weight) are:

$$ \hat{I}_{g,i,t} = q_{i,g,t} \sum{j}{s_{i,j,g}N_{i,j,t}l_{j}W_{i,j,t}} $$

The observed annual index values for each species are assumed to be lognormally distributed around the predicted values:

$$ ln(I_{g,i,t}) \sim \mathcal{N}(ln(\hat{I}_{g,i,t}), \sigma^{2}_{g,i,t}) $$


#### Survey length composition

$$ \hat{p}_{g,i,t,j} = p^{*}_{g,i,t,j} / \sum_{j'}{p^{*}_{g,i,t,j'}} $$

$$ p^{*}_{g,i,t,j} = s_{i,j,g, t} N_{i,j,t} $$

Proportions at length (in numbers) in the survey for each species are modeled as multinomial, with an additional input sample size for each composition.  

#### Prey proportions in survey diet

Proportions by weight in stomach of predator $i$ of size $j$ of prey $m$:

$$ \hat{\phi}_{g,t,i,j,m} = \phi^{*}_{g,t,i,j,m} / \left( \phi^{*}_{g,t,i,j,other} + \sum_{m}{\phi^{*}_{g,t,i,j,m}} \right) $$

$$ \phi^{*}_{g,t,i,j,m} = \sum_{n}{\rho_{i,j,m,n} N_{m,n,t} W_{m,n,t}} $$

Proportions by prey species (in weight) in the survey are modeled as multinomial with an input sample size for each composition (potentially these data could be modeled as Dirichlet or delta-dirichlet, or....)  

<!-- $$ \mathrm{stom}_{g,t,i,j,1:n} \sim \mathrm{Dirichlet} \left( \hat{\phi}_{g,t,i,j,1:n}, \kappa_{i,j} \right) $$ -->

<!-- where $\kappa_{i,j}$ is a parameter for each predator size class. (or input effective sample size if multinomial) -->

### Penalties

#### Recruitment deviations

A penalty to the objective function is added for the annual deviations from the stock-recruitment relationship for each species, which are assumed to be log-normal around the expected recruitment (equation 8):

$$ \Lambda_{i,t} \sim \mathcal{N}\left(0, \tau^{2}_{\Lambda_{i}}\right) $$

where $\tau^{2}_{\Lambda_{i}}$ is the variance of the recruitment deviations for species $i$.

<!-- ### Simulations -->
